### ISSUE TITLE
Rename the repo

### ISSUE THREAD

**Issue by halvardssm** [SocialSlam/wirvsvirus-social-slam#18]
As we are separating frontend and backend into multiple microservices, it might be a good idea to rename this project to represent its content. It might also be good to agree on a naming convention for all the repos/microservices.

Suggestions:
- social-slam-frontend
- social-slam-app
- social-slam-client

**Comment by halvardssm** [comment]
@SocialSlam/developers What do you guys think? What kind of naming scheme should we use for our frontend (this repo) and the backend?

**Comment by Tschakabaka** [comment]
social-slam-frontend would be the most descriptive in my opinion as there could be multiple client applications and def multiple applications in the future

**Comment by halvardssm** [comment]
Sounds good to me 👍
